JanssonDimensions2023.pdf: JanssonDimensions2023.tex
	latexmk -pdf JanssonDimensions2023

JanssonDimensions2023.tex: JanssonDimensions2023.lagda.tex
	lhs2TeX --agda JanssonDimensions2023.lagda.tex > JanssonDimensions2023.tex

