name: basic
on: [push]
jobs:
  check:
    name: Check JanssonDimensionsTalk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wenkokke/setup-agda@latest
        with:
          agda-version: '2.6.4.1'
          agda-stdlib-version: '2.0'
      - working-directory: src
        run: agda JanssonDimensions2022.lagda
      - working-directory: src
        run: agda JanssonDimensions2023.lagda.tex
